### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by rdehuyss** [janjaali/sendGrid-mock#21]
I'm receiving a syntax error in the refactored code:
```
[HPM] Proxy created: /  ->  http://localhost:3000/api
/home/ronald/Projects/BringMe/utils/new-sendgrid-mock/src/server/handler/MailHandler.js:89
[0]   #mails = [];
[0]   ^
[0] 
[0] SyntaxError: Invalid or unexpected token
[0]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by rdehuyss** [comment]
Solved with newer node version
